generatorName: go

gitHost: github.com
gitUserId: greatman
gitRepoId: netbox-go/v4

packageName: netbox

globalProperty:
  apiDocs: false
  modelDocs: false
  apiTests: false
  modelTests: false

typeMappings:
  integer: int64

additionalProperties:
  disallowAdditionalPropertiesIfNotPresent: "false"
  packageVersion: "3"
  enumClassPrefix: true
